### ISSUE TITLE
Remaining tasks for complete RETIS analysis

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#225]
Listing a few remaining tasks, so the current status of #202 can get merged in. Each of these may be separate PRs.

- [x] `RETISTransition.minus_move_flux()` (included in #254; was waiting on #223, fixed by #252)
- [x] `RETISTransition.rate()` (included in #254; requires `minus_move_flux`)
- [x] `RETISTransition.replica_flow()` (included in #250)

**Comment by dwhswenson** [comment]
On further thought, replica flow isn't really best done as a per-transition thing. Rather, I think it is best to include it as part of a suite of utilities for studying replica exchange networks in general. I've been developing that in #250, which now also includes replica flow.

**Comment by jchodera** [comment]
We have some tools for the analysis of replica exchange simulations in YANK that may be of interest.  Some of this is described here:
http://nbviewer.ipython.org/github/choderalab/simulation-health-reports/blob/master/examples/yank/YANK%20analysis%20example.ipynb

**Comment by dwhswenson** [comment]
Thanks @jchodera -- quick question about those: Is there any sort of fundamental "starting point" on which some of the other calculations are based? I'm currently (as in, this evening) working on putting together a matrix that is very similar to the mixing statistics matrix you have; partly in the hopes that it would be a starting point for other approaches (for the graph theory that comes with `networkx`, it ***is*** the starting point for a weighted graph).

The Gelman-Rubin analysis looks particularly interesting. I'll try to structure the analysis routines so that one will be easy to implement. For now I'm just directly implementing the tools that we've frequently used in the past (and, for fun, trying to implement a visualization of the replica exchange network). But I will try to make some other analysis tools easy to add later.

Oh, and new awesomeness in GitHub: did you know you no longer need to send links via nbviewer? Just with the last couple weeks, GitHub natively visualizes ipynbs. https://github.com/choderalab/simulation-health-reports/blob/master/examples/yank/YANK%20analysis%20example.ipynb

**Comment by jchodera** [comment]
> Thanks @jchodera -- quick question about those: Is there any sort of fundamental "starting point" on which some of the other calculations are based? 

Some properties are based on the (symmetrized) empirical state-to-state transition matrix, but others (such as the effective correlation time and equilibration time) are based on the timeseries of the  log of the replica ensemble probability function.

> The Gelman-Rubin analysis looks particularly interesting.

This just requires the ability to perform analysis on either the pooled replica ensembles or individual replicas (which should execute equivalent random walks).

> Oh, and new awesomeness in GitHub: did you know you no longer need to send links via nbviewer? Just with the last couple weeks, GitHub natively visualizes ipynbs.

Yes!  But this functionality is just days old...
